services:
  web:
    build: .
    container_name: geca-admin
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./flask_session:/app/flask_session
    networks:
      - geca-network

networks:
  geca-network:
    driver: bridge