services:
  web:
    build: .
    container_name: geca-admin
    restart: always
    network_mode: "host"
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./flask_session:/app/flask_session
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G