"""shotgun image

Revision ID: 533ebeabb1f4
Revises: f291d462965b
Create Date: 2025-04-21 22:09:28.533494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533ebeabb1f4'
down_revision = 'f291d462965b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shotguns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shotguns', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
