"""Adding user.last_connection/blockerd/is_admin

Revision ID: a0608d7fa755
Revises: 0b2c965f95be
Create Date: 2025-03-17 09:44:31.095127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0608d7fa755'
down_revision = '0b2c965f95be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_connection', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('blocked')
        batch_op.drop_column('last_connection')

    # ### end Alembic commands ###
