name: Debug SSH Connection
on:
  push:
    branches: [ main ]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Debug SSH connection
      run: |
        echo "Current user: $(whoami)"
        echo "SSH directory contents:"
        ls -la ~/.ssh/
        echo "Checking SSH connection..."
        ssh -v -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Connection successful"