name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to server
      env:
        SSH_PASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.APP_DIR }} && git pull && source gecavenv/bin/activate && pip install -r requirements.txt && sudo systemctl restart geca.service"