name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "mkdir -p ~/geca-admin"
          rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" --exclude='.git/' --exclude='.github/' --exclude='.env' ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/geca-admin/

      - name: Create .env file
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cat > ~/geca-admin/.env << 'EOL'
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          SESSION_FILE_DIR=${{ secrets.SESSION_FILE_DIR }}
          DB_URI=${{ secrets.DB_URI }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PWD=${{ secrets.DB_PWD }}
          DB_NAME=${{ secrets.DB_NAME }}
          WHATSAPP_API_KEY=${{ secrets.WHATSAPP_API_KEY }}
          WHATSAPP_API_URL=${{ secrets.WHATSAPP_API_URL }}
          EXPENSE_SCRIPT_ID=${{ secrets.EXPENSE_SCRIPT_ID }}
          INCOME_SCRIPT_ID=${{ secrets.INCOME_SCRIPT_ID }}
          INTERNALTRANSFER_SCRIPT_ID=${{ secrets.INTERNALTRANSFER_SCRIPT_ID }}
          GENERAL_SCRIPT_ID=${{ secrets.GENERAL_SCRIPT_ID }}
          ASKMONEY_SCRIPT_ID=${{ secrets.ASKMONEY_SCRIPT_ID }}
          K3_CELL_VALUE=${{ secrets.K3_CELL_VALUE }}
          IN_MAINTENANCE=${{ secrets.IN_MAINTENANCE }}
          DEVELOP=${{ secrets.DEVELOP }}
          EOL"

      - name: Create credentials.json file
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cat > ~/geca-admin/credentials.json << 'EOL'
          ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          EOL"

      - name: Stop containers
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ~/geca-admin && docker compose down"

      - name: Build containers
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ~/geca-admin && docker compose build"

      - name: Start containers
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ~/geca-admin && docker compose up -d"