name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Git pull latest changes
      env:
        SSH_PASS: ${{ secrets.SSH_PASSWORD }}
      run: sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.APP_DIR }} && git pull"

    - name: Activate virtual environment and install dependencies
      env:
        SSH_PASS: ${{ secrets.SSH_PASSWORD }}
      run: sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.APP_DIR }} && source venv/bin/activate && pip install -r requirements.txt"

    - name: Restart application service
      env:
        SSH_PASS: ${{ secrets.SSH_PASSWORD }}
      run: sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl restart geca.service"