name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH known hosts
        run: |
          mkdir -p ~/.ssh
          run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy repository to server
        run: |
          rsync -avz --exclude '.git' --exclude '.github' . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/geca-admin

      - name: Create env file
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/geca-admin
            cat > .env << 'EOL'
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            SESSION_FILE_DIR=${{ secrets.SESSION_FILE_DIR }}
            DB_URI=${{ secrets.DB_URI }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PWD=${{ secrets.DB_PWD }}
            DB_NAME=${{ secrets.DB_NAME }}
            WHATSAPP_API_KEY=${{ secrets.WHATSAPP_API_KEY }}
            WHATSAPP_API_URL=${{ secrets.WHATSAPP_API_URL }}
            EXPENSE_SCRIPT_ID=${{ secrets.EXPENSE_SCRIPT_ID }}
            INCOME_SCRIPT_ID=${{ secrets.INCOME_SCRIPT_ID }}
            INTERNALTRANSFER_SCRIPT_ID=${{ secrets.INTERNALTRANSFER_SCRIPT_ID }}
            GENERAL_SCRIPT_ID=${{ secrets.GENERAL_SCRIPT_ID }}
            ASKMONEY_SCRIPT_ID=${{ secrets.ASKMONEY_SCRIPT_ID }}
            K3_CELL_VALUE=${{ secrets.K3_CELL_VALUE }}
            IN_MAINTENANCE=${{ secrets.IN_MAINTENANCE }}
            DEVELOP=${{ secrets.DEVELOP }}
            EOL
            
            # Create the credentials.json file with Google API credentials
            cat > credentials.json << 'EOL'
            ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
            EOL

      - name: Deploy and restart application
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/geca-admin
            docker-compose down
            docker-compose build
            docker-compose up -d
            echo "Deployment completed successfully"